version: "3"
services:
  project:
    image: sps
    container_name: sps_container
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ipc: host
    network_mode: host
    volumes:
      - ${PWD}/:/sps
      - ${DATA}:/sps/data
    stdin_open: true
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_MASTER_URI=$ROS_MASTER_URI
    working_dir: /sps