DATA:
  NUM_WORKER: 4
  SHUFFLE: true
  SPLIT:
    TEST:
    - scene-0162
    TRAIN:
    - scene-0162
    VAL:
    - scene-0162
  
  MAPS:
    TEST:
    - scene-0162
    TRAIN:
    - scene-0162
    VAL:
    - scene-0162
EXPERIMENT:
  ID: NUSCENES_TEST_0162
FILTER:
  THRESHOLD: 0.84
MODEL:
  RADAR_FEATURES: True
  VOXEL_SIZE: 0.1
TRAIN:
  AUGMENTATION: false
  BATCH_SIZE: 1
  LR: 0.001
  LR_DECAY: 0.99
  LR_EPOCH: 100
  MAP: ''
  MAX_EPOCH: 100
  WEIGHT_DECAY: 0.0001
